### ISSUE TITLE
XMI - tempo change

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/wildmidi#108]
@chrisisonwildcode said "Noticed that xmidi.c only uses the first tempo change and ignores all others. Issue?"

Do we have example VMI files that change tempo?  

Could this have anything to do with this issue: https://github.com/Mindwerks/wildmidi/issues/107
^-- Relates to converted types (mt32-to-GM/GS) "This is only suitable for music that doesn't do timbre changes XMIDIs that contain Timbre changes will not convert properly. "

**Comment by chrisisonwildcode** [comment]
The "Timbre" is throwing me off ... I think what they are referring to is that the xmi files have patch settings outside of the MIDI data (although in my tests the MIDI data also contained patch settings) ... so I speculate that its something to do with those, however because all the XMI's I tested contained patch information in the MIDI data, I ignored the patch settings outside of the MIDI data. If it later becomes an issue I can fix.

If we ever do find a xmi with tempo change, the player and associated dump (pressing 'm' while playing) will honour the tempo change, however the converter in xmidi.c which is used when you convert without playing will not.

**Comment by psi29a** [comment]
Not sure if relevant, but this xmi sounds off on your branch in comparison to master. The result of your branch yields output that is slow... (double the length).

I'll email it to everyone. Don't have dropbox handy at the moment.

**Comment by chrisisonwildcode** [comment]
Based on recorded in game audio and the finding of an XMI with a tempo change within it, -updates now only uses the first tempo setting within an XMI and ignores all others. This now matches the behaviour of the xmidi.c code when it comes to tempo changes.

Going to close this as the original reason for ticket is now sorted.
