### ISSUE TITLE
kyra1a.mid doesn't play with current wildmidi-master

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#125]
kyra1a.mid (exported from xmi using an old version of wildmidi-master)
doesn't play with current wildmidi-master. it does with wildmidi-0.3.8,
and it also plays with timidity. wildmidi-master reports a crazy total
time of 1469m 35s, but 0.3.8 reports normally 12m 35s. Sent the file to
Chris's personal email. The behavior is the same if I export kyra1a.xmi
from Legend of Kyrandia using current master with a cmdline like:
./wildmidi -c mytimidity.cfg -x kyra1a.mid -g 1 kyra1a.xmi

**Comment by psi29a** [comment]
Most of kyra are so-called type2 xmi files. Lots of tracks actually, like looping tracks for one song.

**Comment by sezero** [comment]
Didn't try other kyra songs yet, therefore I don't know if this something with this particular song or with any type2 songs.

**Comment by chrisisonwildcode** [comment]
Will keep this in mind ...

**Comment by chrisisonwildcode** [comment]
Can you please pass me a link to kyra xmi's?

**Comment by psi29a** [comment]
http://www.vgmpf.com/Wiki/index.php?title=The_Legend_of_Kyrandia:_Book_One_(DOS)
http://www.vgmpf.com/Wiki/images/2/23/Legend_of_Kyrandia%2C_The_-_Book_1_%28DOS%29.zip

**Comment by sezero** [comment]
I exported all kyra xmi files using current master with a cmdline like:
./wildmidi -c mytimidity.cfg -x kyraXXX.mid -g 1 kyraXXX.xmi
and the playback behavior of the resulting midis are the same. The -g1
switch doesn't change anything.

Don't know if this is anything specific to kyra files, or type2 files.

**Comment by chrisisonwildcode** [comment]
I think I might have screwed up the type 2 midi parsing ... looking into it further ... on a related note the xmi plays fine however there is a descrepency between the devtest time and player time. Will look into this I work out where I may have screwed up ...

**Comment by chrisisonwildcode** [comment]
Working on this today. 

Relevant to this I will be adding a command line option to write output midi file as type 2 when input was type 2 midi or XMI, otherwise output will be type 0 midi. Again to output midi type 2, you will need to set a command line option (in the player) and the input data has to be in midi type 2 format or XMI.

Along with this a new API function will be developed. 
WM_SYMBOL int WildMidi_SongSeek (midi * handle, int8_t nextsong);

If output type is type 2 then 
- if nextsong is > 0 then the library seeks to the next song in the data
- if nextsong is < 0  then library seeks to previous song
- if nextsong is 0 then library seeks back to start of current song
otherwise does nothing.

**Comment by psi29a** [comment]
So you figured out what was wrong and as a result will be handling type 2 differently from the rest?

Basically, by default when you dump a type2 (whatever) to a midi file... it will default to a long type 0? If you wish to keep type2, it will have to explicitly set that? 

We will still auto detect a type2 and play it back as a type0 though?

**Comment by chrisisonwildcode** [comment]
Type 2 midi loading has has some rework done to it ... must have had my mind elsewhere when I initially wrote it. Upon debugging the crap out of it I discovered some weird things going on and had to fix up other areas for it all to work flawlessly. I am still testing and ironing out the bugs.

Yes, it auto-detects type 2 midi, and XMI with multiple event forms are treated as type 2 as well. The confusing thing about XMI is the one I am using for testing has 121 event forms, all on which have midi events, only a few contain notes. I will be keeping an eye on xmi files like this to determine if I need to add any additional processing to the todo list.

It can auto dump to type 2 if it is detected, if that would be better for you. Then we would only need a command line to dump as type 2 midi. Some people may have issue with this as more popular editors cannot handle type 2 midi files, this is why I was defaulting to type 0 midi files. But I'm happy to make the switch go the other way :)

At the moment I am testing the dumping to type 2 midi, I must be getting tired because of the type of mistakes I am encountering.

**Comment by sezero** [comment]
Does the wildmidi-0.3 version of type-2 loader need any fixing?

**Comment by chrisisonwildcode** [comment]
@sezero I have still to look at the 0.3 codebase ...

As for 0.4 ... I have a fix ready but there is a issue which I wish you guys opinion about.

With type 2 files it is possible to have zero notes within a track (evident in the kyara files). This mucks up being able to rewind to the previous track because those tracks are so fast that it is already on the next track before you can hit the rewind key. So pressing the key to go to previous song just lands you back at the track with 0 notes and on to the next track. On the surface it looks like it doesn't rewind, under the hood it does but the track is too fast.

Do we want to merge tracks with 0 notes with the next track that follows them? Or we cal tell ppl to rewind using ',' to get to a point before the 0 note track then hit '/' or '<' ...

I can add a flag to make the merge optional, just looking at it from a 'sanity of user' point of view.

**Comment by chrisisonwildcode** [comment]
See midi-type-2-fix branch.

**Comment by psi29a** [comment]
This is some head scratching stuff, type 2 (like type 2 midis) where meant as a way to handle loops and advanced trickery and rarely used. I'm assuming that those tracks are there on purpose and for a reason, perhaps as timing or pauses. However, since we don't know how the tracks are supposed to be 'composed'... we just want to play ever track as-is.

I'm voting for making merging optional. If we are to 'keep true to the midi' philosophy, then we should do that for playback as well, unless explicitly asked for it.

What do you guys think?

**Comment by sezero** [comment]
On 3/1/15, Bret Curtis <notifications@github.com> wrote:
> This is some head scratching stuff, type 2 (like type 2 midis) where meant
> as a way to handle loops and advanced trickery and rarely used. I'm assuming
> that those tracks are there on purpose and for a reason, perhaps as timing
> or pauses. However, since we don't know how the tracks are supposed to be
> 'composed'... we just want to play ever track as-is.
>
> I'm voting for making merging optional. If we are to 'keep true to the midi'
> philosophy, then we should do that for playback as well, unless explicitly
> asked for it.
>
> What do you guys think?

Agreed.

**Comment by chrisisonwildcode** [comment]
Ok, so I'll add to my todo list an option to merge zero note tracks in type 2 style files with the next track.

In the mean time please test and merge the type 2 fix

**Comment by psi29a** [comment]
Just tested the midi-type-2-fix branch with kyra1a.xmi:

it plays immediatly and is 12m 38s long.  The resulting midi says it is 2101m 17s long.

Derp!

Something isn't right here.

**Comment by chrisisonwildcode** [comment]
Hrrm will look again but kyra1a.xmi is one of the ones I've been testing with ... I'll have a look ...

**Comment by chrisisonwildcode** [comment]
Not fixed yet but ...

I had originally had this fixed, while I am not sure what happened I believe a github update (locally) may be at fault for unfixing it. There was a gap between my testing and my publishing the fix ... github had updated and some of my previous work got wiped during the update. Only realised it had updated when I tried to sync this morning and github was complaining about the build directory, and the commit section of the github app is visually different.

**Comment by chrisisonwildcode** [comment]
I am going to attempt to make some changes to f_midi.c and see if that helps. Changes will be around midi loading ... Cross fingers because I will be doing this from the iPad.

**Comment by psi29a** [comment]
*crosses fingers and toes*

Though I've never heard of that issue with github, but if you are working with such handicaps... no worries! ;)

**Comment by chrisisonwildcode** [comment]
Please test midi-type-2-fix

**Comment by sezero** [comment]
On 3/11/15, chrisisonwildcode <notifications@github.com> wrote:
> Please test midi-type-2-fix
>

The branch seems to have fixed the type2 issue.
Tried a few type 0/1/2 midis, all played ok for me.

**Comment by sezero** [comment]
Merged the branch into master, removed the branch. Closing this bug.
