### ISSUE TITLE
make a new 0.4.1 bug-fix release

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#142]
We should make a 0.4.1 followup bugfix release:
One bug I fixed is commit 335dc04.
Bug #141 stands out, which is waiting for @chrisisonwildcode

**Comment by psi29a** [comment]
Sure, when @chrisisonwildcode fixes that we should do a 0.4.1

I'm awaiting debian/ubuntu to flood us with bugs as well.

**Comment by psi29a** [comment]
After https://github.com/Mindwerks/wildmidi/issues/141 is fixed, should we do a 0.4.1 release or wait a bit more?

**Comment by sezero** [comment]
Don't have strong opinion for it.

**Comment by chrisisonwildcode** [comment]
Wait a bit more.

I've looked through the code and saw nothing obvious, as in the code paths for selecting a song within a multi-song file show no obvious errors. I'll be looking at the files that were sent later today and if they show nothing we've missed then I'll be gdbing the thing and tracing what's going on.

At the very least I'll have an answer today, at most a fix.

**Comment by psi29a** [comment]
BTW:  https://github.com/afritz1/OpenTESArena/issues/38#issuecomment-229791239

Most of this was answered by Chris/Kcat (OpenAL-Soft dev), please give it a once over to see if he was correct? It implies that XMI support is only partial because it doesn't support a translation of XMI's looping mechanism.

There are at least 2 files that seem to go on forever. One with 4~5m pause and another with an hour pause.

Apparently freepats has missing instruments which might cause problems for other users of WildMIDI.

**Comment by chrisisonwildcode** [comment]
I'm going to look into this. I'm sure we can support xmi loops converted into custom midi instructions ... Aka meta events ... Or even custom controller everts.

If it can be pulled off the way I'm thinking then XMI's converted to MIDI via wildmidi would playback converted xmi loops as loops. Of course we'd need an option to ignore/enable loops for sanity.

Thoughts?

**Comment by chrisisonwildcode** [comment]
I can add support for xmidi controllers 116 & 117 and have WildMIDI support those from its midi output. But we're going to need a "gate keeper" for the midi output due to those controllers being undefined in midi and therefore ignored by default to avoid undesirable behaviours. We could add a text meta event "XMIDI" to be that gate keeper at the start of the file to denote xmidi controllers 116 & 117 be enabled.

Again thoughts

**Comment by psi29a** [comment]
Possibly related? https://github.com/Mindwerks/wildmidi/issues/146

Looks like there are some unimplemented (looping based) MIDI messages/events.

**Comment by psi29a** [comment]
From doing my work with OpenBSD, it told me the following:

```
Scanning dependencies of target wildmidi
[ 90%] Building C object src/CMakeFiles/wildmidi.dir/wm_tty.c.o
[ 95%] Building C object src/CMakeFiles/wildmidi.dir/wildmidi.c.o
[100%] Linking C executable ../wildmidi
CMakeFiles/wildmidi.dir/wildmidi.c.o: In function `open_oss_output':
/home/psi29a/WildMIDI/wildmidi/src/wildmidi.c:1052: warning: warning: strcpy() is almost always misused, please use strlcpy()
/home/psi29a/WildMIDI/build/libWildMidi.so.2.0: warning: warning: vsprintf() is often misused, please use vsnprintf()
/home/psi29a/WildMIDI/build/libWildMidi.so.2.0: warning: warning: strcat() is almost always misused, please use strlcat()
/home/psi29a/WildMIDI/build/libWildMidi.so.2.0: warning: warning: sprintf() is often misused, please use snprintf()
[100%] Built target wildmidi
```

Something to worry about? Good advise? Will we break something?

**Comment by sezero** [comment]
strlcat warning is an openbsd advice. The rest are common advice.
If we are manipulating our buffers correctly, then there is nothing to
worry about. (That also means that it wouldn't hurt revisiting those
parts of the code and revising.)

**Comment by psi29a** [comment]
Great news: https://buildd.debian.org/status/package.php?p=wildmidi

0.4.0 is finally uploaded to debian and it is built on all known platforms!  (note, no tests were performed other than being built)

**Comment by sezero** [comment]
On 8/16/16, Bret Curtis <notifications@github.com> wrote:
> Great news: https://buildd.debian.org/status/package.php?p=wildmidi
>
> 0.4.0 is finally uploaded to debian and it is built on all known platforms!
> (note, no tests were performed other than being built)

Are packages depending on libwildmidi proted properly too?
The big endian target will be affected most importantly.

**Comment by psi29a** [comment]
Slomo (Debian) knows of the API changes, so that has been taken care of for us.

**Comment by sezero** [comment]
Should we make a 0.4.1 release? None of the open bug reports are regressions, including #141, already.

**Comment by chrisisonwildcode** [comment]
Sorry for delays, life and all that comes with it.

I'll be looking into features and bugs this week as I will have plenty of time on my hands. Hope to resolve at least #146 #149 #158

Chris

**Comment by psi29a** [comment]
rejoice! :)

**Comment by psi29a** [comment]
I'm looking to, with @sezero blessing, begin work on on unsf integration so that we have some support for  sf2. This will likely be for 0.4.2 unless 0.4.1 is still not yet released by the time I'm ready to merge. ;)

**Comment by sezero** [comment]
On 10/3/16, Bret Curtis <notifications@github.com> wrote:
> I'm looking to, with @sezero blessing, begin work on on unsf integration so
> that we have some support for  sf2. This will likely be for 0.4.2 unless
> 0.4.1 is still not yet released by the time I'm ready to merge. ;)

My _blessing_ (oh boy..) is irrelevant, but there is an inherent
issue with unsf as it is, which you know too: it wants to extract
the whole thing into files, bu we want to get the only samples
we want in a memory area. unsf shall need modifying heavily
for it.

**Comment by psi29a** [comment]
I was just _trying_ to be funny. ;)  

Three things:
1) once the whole soundfont is extracted, we don't need to do it again. This is why I implemented the -o flag, so that we can dump it to /tmp (or other directory dependent on OS). This creates the cfg file that will be read into wildmidi. 

2) specifically asking for a patch/sample is on my todo list, but as an additional API call that gives a memory buffer location. So we would then explictely need to call open and close APIs. This is a lot more work, but worth it.

3) unsf isn't a replacement for native support for sf2, just a stop-gap. it was always my intention, at least in the beginning, to unpack the whole soundfont.

**Comment by sezero** [comment]
Any chance that we'll see those bug fixes? Or should we make a bugfix release from what we already have?

**Comment by psi29a** [comment]
@chrisisonwildcode I think he was referring to #146 #149 #158

**Comment by chrisisonwildcode** [comment]
Yes, we will see these fixes on Sunday night (AEST). I have been really busy with life, I apologise for the delay.

**Comment by sezero** [comment]
#149 and #158 are more important. #146 is a new feature which everybody can live (and have been living) without.

**Comment by chrisisonwildcode** [comment]
I am dedicating this week to get stuff happening. I must point out that fixing devtest has been a priority due to it having timing issues making it harder to debug formats.

Plan is to:
- Fix devtest (fix timing issue to make debugging formats easier)
- Fix playback of xmi loops
- Implement midi event callback (note this will trigger on the event but before it is processed by WildMIDI)
- Fix playback of other formats

Any other request for the next release then please speak up.

**Comment by sezero** [comment]
Do we have an ETA yet?

**Comment by sezero** [comment]
Will this take forever?

**Comment by chrisisonwildcode** [comment]
Hi,

I do apologise. To be honest with myself I haven't had the motivation lately to do much. In saying that I am getting back on track however I am having an operation in a couple of days time. The recovery period after release from hospital will give me plenty of time to work on this.

I will give you an eta of 3-6 weeks dependent on my recovery.

Again sorry for the delay.

Sincerely
Chris

**Comment by psi29a** [comment]
Gives me time to sneak in some stuff. ;)

**Comment by sezero** [comment]
Nothing is happening. Should we release what we have as 0.4.1 ?

**Comment by chrisisonwildcode** [comment]
Sorry, I know I keep saying that then something in my other life happens. If you want to release do so, I will be bug fixing as time allows. I have been working on stuff but have nothing ready.

Chris

**Comment by sezero** [comment]
Made the 0.4.1 release; also created a new "0.4.2" milestone. Closing this one.
