### ISSUE TITLE
Make configuration file optional

### ISSUE THREAD

**Issue by schickst** [Mindwerks/wildmidi#209]
Hey, 

in the ArchLinux Bugtracker is an old issue:
https://bugs.archlinux.org/task/47508?project=1&only_watched=1&pagenum=1&order=dateopened&sort=desc

The error message is as follows:
Tested with with WildMidi 0.4.3
System Error (_WM_BufferFileImpl:218) /etc/wildmidi/wildmidi.cfg (Unable to stat) : No such file or directory

It seems ArchLinux isn't providing a config file in its package. In the comments it is mentioned, that wildmidi is working fine with an empty config file. 

While Arch isn't packaging it correctly, there is a better solution. Because of this, I propose to make the config file optional. I see no use in requiring a config file, which can be empty.

**Comment by Oreo639** [comment]
The config file is needed because it tells WildMidi where to find the GUS patchsets.
You could just install freepats. I would imagine it would come with an example config, which you can copy to `/etc/wildmidi/wildmdi.cfg`
Although you don't need to install freepats, as you can use a different config with different timidity/wildmidi compatible patchsets, but they are needed for sound output, so I don't see the issue.

With an empty config file, while it would work, it wouldn't play any sound as it needs the patchsets to get the samples.

Maybe I am misunderstanding you though.

(Not a maintainer for the repo, just giving some context)

**Comment by legluondunet** [comment]
another solution would be to add a command option to precise config file path? Perhaps is it already possible?

**Comment by sezero** [comment]
The config file is needed for the GUS patches. If a distro isn't providing a proper config file, it's their problem.  Closing this as invalid.
