### ISSUE TITLE
It says this isn't a valid midi file when I try to convert it with Wildmidi

### ISSUE THREAD

**Issue by Videogamer555** [Mindwerks/wildmidi#233]
It's supposed to be a valid midi file. If this is just an alternate format of midi file, please consider adding support for it.
https://ufile.io/c3mpgqfd

**Comment by sezero** [comment]
It isn't supported for sure. `file` reports this:
```
$ file music1.mid
music1.mid: Apple QuickTime movie (unoptimized)
```
Whatever it is, we'll need documentation at the least,
Don't know any one would volunteer for this - I won't.

In any case, attaching the file here so that it won't get lost.
[music1.mid.zip](https://github.com/Mindwerks/wildmidi/files/7832841/music1.mid.zip)

**Comment by sezero** [comment]
It does seem some Apple QuickTime crapola - format documentation:
https://developer.apple.com/standards/qtff-2001.pdf

I am not ever going to work on this.  @psi29a: We can close this, unless
you volunteer for it.

**Comment by sezero** [comment]
Closing. If someone really wants to work on this in future, then re-open.
